// Pokémon da região de Johto (Pokédex Nacional Nº 152–251).
// type usa as chaves em inglês (para cores/sprites); o rótulo PT vem de TYPE_LABELS.
const TYPE_LABELS = {
  normal: "Normal", fire: "Fogo", water: "Água", grass: "Planta",
  electric: "Elétrico", ice: "Gelo", fighting: "Lutador", poison: "Veneno",
  ground: "Terra", flying: "Voador", psychic: "Psíquico", bug: "Inseto",
  rock: "Pedra", ghost: "Fantasma", dragon: "Dragão", dark: "Noturno",
  steel: "Aço", fairy: "Fada",
};

const KANTO = [
  { id: 1, name: "Bulbasaur", types: ["grass", "poison"] },
  { id: 2, name: "Ivysaur", types: ["grass", "poison"] },
  { id: 3, name: "Venusaur", types: ["grass", "poison"] },
  { id: 4, name: "Charmander", types: ["fire"] },
  { id: 5, name: "Charmeleon", types: ["fire"] },
  { id: 6, name: "Charizard", types: ["fire", "flying"] },
  { id: 7, name: "Squirtle", types: ["water"] },
  { id: 8, name: "Wartortle", types: ["water"] },
  { id: 9, name: "Blastoise", types: ["water"] },
  { id: 10, name: "Caterpie", types: ["bug"] },
  { id: 11, name: "Metapod", types: ["bug"] },
  { id: 12, name: "Butterfree", types: ["bug", "flying"] },
  { id: 13, name: "Weedle", types: ["bug", "poison"] },
  { id: 14, name: "Kakuna", types: ["bug", "poison"] },
  { id: 15, name: "Beedrill", types: ["bug", "poison"] },
  { id: 16, name: "Pidgey", types: ["normal", "flying"] },
  { id: 17, name: "Pidgeotto", types: ["normal", "flying"] },
  { id: 18, name: "Pidgeot", types: ["normal", "flying"] },
  { id: 19, name: "Rattata", types: ["normal"] },
  { id: 20, name: "Raticate", types: ["normal"] },
  { id: 21, name: "Spearow", types: ["normal", "flying"] },
  { id: 22, name: "Fearow", types: ["normal", "flying"] },
  { id: 23, name: "Ekans", types: ["poison"] },
  { id: 24, name: "Arbok", types: ["poison"] },
  { id: 25, name: "Pikachu", types: ["electric"] },
  { id: 26, name: "Raichu", types: ["electric"] },
  { id: 27, name: "Sandshrew", types: ["ground"] },
  { id: 28, name: "Sandslash", types: ["ground"] },
  { id: 29, name: "Nidoran♀", types: ["poison"] },
  { id: 30, name: "Nidorina", types: ["poison"] },
  { id: 31, name: "Nidoqueen", types: ["poison", "ground"] },
  { id: 32, name: "Nidoran♂", types: ["poison"] },
  { id: 33, name: "Nidorino", types: ["poison"] },
  { id: 34, name: "Nidoking", types: ["poison", "ground"] },
  { id: 35, name: "Clefairy", types: ["fairy"] },
  { id: 36, name: "Clefable", types: ["fairy"] },
  { id: 37, name: "Vulpix", types: ["fire"] },
  { id: 38, name: "Ninetales", types: ["fire"] },
  { id: 39, name: "Jigglypuff", types: ["normal", "fairy"] },
  { id: 40, name: "Wigglytuff", types: ["normal", "fairy"] },
  { id: 41, name: "Zubat", types: ["poison", "flying"] },
  { id: 42, name: "Golbat", types: ["poison", "flying"] },
  { id: 43, name: "Oddish", types: ["grass", "poison"] },
  { id: 44, name: "Gloom", types: ["grass", "poison"] },
  { id: 45, name: "Vileplume", types: ["grass", "poison"] },
  { id: 46, name: "Paras", types: ["bug", "grass"] },
  { id: 47, name: "Parasect", types: ["bug", "grass"] },
  { id: 48, name: "Venonat", types: ["bug", "poison"] },
  { id: 49, name: "Venomoth", types: ["bug", "poison"] },
  { id: 50, name: "Diglett", types: ["ground"] },
  { id: 51, name: "Dugtrio", types: ["ground"] },
  { id: 52, name: "Meowth", types: ["normal"] },
  { id: 53, name: "Persian", types: ["normal"] },
  { id: 54, name: "Psyduck", types: ["water"] },
  { id: 55, name: "Golduck", types: ["water"] },
  { id: 56, name: "Mankey", types: ["fighting"] },
  { id: 57, name: "Primeape", types: ["fighting"] },
  { id: 58, name: "Growlithe", types: ["fire"] },
  { id: 59, name: "Arcanine", types: ["fire"] },
  { id: 60, name: "Poliwag", types: ["water"] },
  { id: 61, name: "Poliwhirl", types: ["water"] },
  { id: 62, name: "Poliwrath", types: ["water", "fighting"] },
  { id: 63, name: "Abra", types: ["psychic"] },
  { id: 64, name: "Kadabra", types: ["psychic"] },
  { id: 65, name: "Alakazam", types: ["psychic"] },
  { id: 66, name: "Machop", types: ["fighting"] },
  { id: 67, name: "Machoke", types: ["fighting"] },
  { id: 68, name: "Machamp", types: ["fighting"] },
  { id: 69, name: "Bellsprout", types: ["grass", "poison"] },
  { id: 70, name: "Weepinbell", types: ["grass", "poison"] },
  { id: 71, name: "Victreebel", types: ["grass", "poison"] },
  { id: 72, name: "Tentacool", types: ["water", "poison"] },
  { id: 73, name: "Tentacruel", types: ["water", "poison"] },
  { id: 74, name: "Geodude", types: ["rock", "ground"] },
  { id: 75, name: "Graveler", types: ["rock", "ground"] },
  { id: 76, name: "Golem", types: ["rock", "ground"] },
  { id: 77, name: "Ponyta", types: ["fire"] },
  { id: 78, name: "Rapidash", types: ["fire"] },
  { id: 79, name: "Slowpoke", types: ["water", "psychic"] },
  { id: 80, name: "Slowbro", types: ["water", "psychic"] },
  { id: 81, name: "Magnemite", types: ["electric", "steel"] },
  { id: 82, name: "Magneton", types: ["electric", "steel"] },
  { id: 83, name: "Farfetch'd", types: ["normal", "flying"] },
  { id: 84, name: "Doduo", types: ["normal", "flying"] },
  { id: 85, name: "Dodrio", types: ["normal", "flying"] },
  { id: 86, name: "Seel", types: ["water"] },
  { id: 87, name: "Dewgong", types: ["water", "ice"] },
  { id: 88, name: "Grimer", types: ["poison"] },
  { id: 89, name: "Muk", types: ["poison"] },
  { id: 90, name: "Shellder", types: ["water"] },
  { id: 91, name: "Cloyster", types: ["water", "ice"] },
  { id: 92, name: "Gastly", types: ["ghost", "poison"] },
  { id: 93, name: "Haunter", types: ["ghost", "poison"] },
  { id: 94, name: "Gengar", types: ["ghost", "poison"] },
  { id: 95, name: "Onix", types: ["rock", "ground"] },
  { id: 96, name: "Drowzee", types: ["psychic"] },
  { id: 97, name: "Hypno", types: ["psychic"] },
  { id: 98, name: "Krabby", types: ["water"] },
  { id: 99, name: "Kingler", types: ["water"] },
  { id: 100, name: "Voltorb", types: ["electric"] },
  { id: 101, name: "Electrode", types: ["electric"] },
  { id: 102, name: "Exeggcute", types: ["grass", "psychic"] },
  { id: 103, name: "Exeggutor", types: ["grass", "psychic"] },
  { id: 104, name: "Cubone", types: ["ground"] },
  { id: 105, name: "Marowak", types: ["ground"] },
  { id: 106, name: "Hitmonlee", types: ["fighting"] },
  { id: 107, name: "Hitmonchan", types: ["fighting"] },
  { id: 108, name: "Lickitung", types: ["normal"] },
  { id: 109, name: "Koffing", types: ["poison"] },
  { id: 110, name: "Weezing", types: ["poison"] },
  { id: 111, name: "Rhyhorn", types: ["ground", "rock"] },
  { id: 112, name: "Rhydon", types: ["ground", "rock"] },
  { id: 113, name: "Chansey", types: ["normal"] },
  { id: 114, name: "Tangela", types: ["grass"] },
  { id: 115, name: "Kangaskhan", types: ["normal"] },
  { id: 116, name: "Horsea", types: ["water"] },
  { id: 117, name: "Seadra", types: ["water"] },
  { id: 118, name: "Goldeen", types: ["water"] },
  { id: 119, name: "Seaking", types: ["water"] },
  { id: 120, name: "Staryu", types: ["water"] },
  { id: 121, name: "Starmie", types: ["water", "psychic"] },
  { id: 122, name: "Mr. Mime", types: ["psychic", "fairy"] },
  { id: 123, name: "Scyther", types: ["bug", "flying"] },
  { id: 124, name: "Jynx", types: ["ice", "psychic"] },
  { id: 125, name: "Electabuzz", types: ["electric"] },
  { id: 126, name: "Magmar", types: ["fire"] },
  { id: 127, name: "Pinsir", types: ["bug"] },
  { id: 128, name: "Tauros", types: ["normal"] },
  { id: 129, name: "Magikarp", types: ["water"] },
  { id: 130, name: "Gyarados", types: ["water", "flying"] },
  { id: 131, name: "Lapras", types: ["water", "ice"] },
  { id: 132, name: "Ditto", types: ["normal"] },
  { id: 133, name: "Eevee", types: ["normal"] },
  { id: 134, name: "Vaporeon", types: ["water"] },
  { id: 135, name: "Jolteon", types: ["electric"] },
  { id: 136, name: "Flareon", types: ["fire"] },
  { id: 137, name: "Porygon", types: ["normal"] },
  { id: 138, name: "Omanyte", types: ["rock", "water"] },
  { id: 139, name: "Omastar", types: ["rock", "water"] },
  { id: 140, name: "Kabuto", types: ["rock", "water"] },
  { id: 141, name: "Kabutops", types: ["rock", "water"] },
  { id: 142, name: "Aerodactyl", types: ["rock", "flying"] },
  { id: 143, name: "Snorlax", types: ["normal"] },
  { id: 144, name: "Articuno", types: ["ice", "flying"] },
  { id: 145, name: "Zapdos", types: ["electric", "flying"] },
  { id: 146, name: "Moltres", types: ["fire", "flying"] },
  { id: 147, name: "Dratini", types: ["dragon"] },
  { id: 148, name: "Dragonair", types: ["dragon"] },
  { id: 149, name: "Dragonite", types: ["dragon", "flying"] },
  { id: 150, name: "Mewtwo", types: ["psychic"] },
  { id: 151, name: "Mew", types: ["psychic"] },
];

const JOHTO = [
  { id: 152, name: "Chikorita", types: ["grass"] },
  { id: 153, name: "Bayleef", types: ["grass"] },
  { id: 154, name: "Meganium", types: ["grass"] },
  { id: 155, name: "Cyndaquil", types: ["fire"] },
  { id: 156, name: "Quilava", types: ["fire"] },
  { id: 157, name: "Typhlosion", types: ["fire"] },
  { id: 158, name: "Totodile", types: ["water"] },
  { id: 159, name: "Croconaw", types: ["water"] },
  { id: 160, name: "Feraligatr", types: ["water"] },
  { id: 161, name: "Sentret", types: ["normal"] },
  { id: 162, name: "Furret", types: ["normal"] },
  { id: 163, name: "Hoothoot", types: ["normal", "flying"] },
  { id: 164, name: "Noctowl", types: ["normal", "flying"] },
  { id: 165, name: "Ledyba", types: ["bug", "flying"] },
  { id: 166, name: "Ledian", types: ["bug", "flying"] },
  { id: 167, name: "Spinarak", types: ["bug", "poison"] },
  { id: 168, name: "Ariados", types: ["bug", "poison"] },
  { id: 169, name: "Crobat", types: ["poison", "flying"] },
  { id: 170, name: "Chinchou", types: ["water", "electric"] },
  { id: 171, name: "Lanturn", types: ["water", "electric"] },
  { id: 172, name: "Pichu", types: ["electric"] },
  { id: 173, name: "Cleffa", types: ["fairy"] },
  { id: 174, name: "Igglybuff", types: ["normal", "fairy"] },
  { id: 175, name: "Togepi", types: ["fairy"] },
  { id: 176, name: "Togetic", types: ["fairy", "flying"] },
  { id: 177, name: "Natu", types: ["psychic", "flying"] },
  { id: 178, name: "Xatu", types: ["psychic", "flying"] },
  { id: 179, name: "Mareep", types: ["electric"] },
  { id: 180, name: "Flaaffy", types: ["electric"] },
  { id: 181, name: "Ampharos", types: ["electric"] },
  { id: 182, name: "Bellossom", types: ["grass"] },
  { id: 183, name: "Marill", types: ["water", "fairy"] },
  { id: 184, name: "Azumarill", types: ["water", "fairy"] },
  { id: 185, name: "Sudowoodo", types: ["rock"] },
  { id: 186, name: "Politoed", types: ["water"] },
  { id: 187, name: "Hoppip", types: ["grass", "flying"] },
  { id: 188, name: "Skiploom", types: ["grass", "flying"] },
  { id: 189, name: "Jumpluff", types: ["grass", "flying"] },
  { id: 190, name: "Aipom", types: ["normal"] },
  { id: 191, name: "Sunkern", types: ["grass"] },
  { id: 192, name: "Sunflora", types: ["grass"] },
  { id: 193, name: "Yanma", types: ["bug", "flying"] },
  { id: 194, name: "Wooper", types: ["water", "ground"] },
  { id: 195, name: "Quagsire", types: ["water", "ground"] },
  { id: 196, name: "Espeon", types: ["psychic"] },
  { id: 197, name: "Umbreon", types: ["dark"] },
  { id: 198, name: "Murkrow", types: ["dark", "flying"] },
  { id: 199, name: "Slowking", types: ["water", "psychic"] },
  { id: 200, name: "Misdreavus", types: ["ghost"] },
  { id: 201, name: "Unown", types: ["psychic"] },
  { id: 202, name: "Wobbuffet", types: ["psychic"] },
  { id: 203, name: "Girafarig", types: ["normal", "psychic"] },
  { id: 204, name: "Pineco", types: ["bug"] },
  { id: 205, name: "Forretress", types: ["bug", "steel"] },
  { id: 206, name: "Dunsparce", types: ["normal"] },
  { id: 207, name: "Gligar", types: ["ground", "flying"] },
  { id: 208, name: "Steelix", types: ["steel", "ground"] },
  { id: 209, name: "Snubbull", types: ["fairy"] },
  { id: 210, name: "Granbull", types: ["fairy"] },
  { id: 211, name: "Qwilfish", types: ["water", "poison"] },
  { id: 212, name: "Scizor", types: ["bug", "steel"] },
  { id: 213, name: "Shuckle", types: ["bug", "rock"] },
  { id: 214, name: "Heracross", types: ["bug", "fighting"] },
  { id: 215, name: "Sneasel", types: ["dark", "ice"] },
  { id: 216, name: "Teddiursa", types: ["normal"] },
  { id: 217, name: "Ursaring", types: ["normal"] },
  { id: 218, name: "Slugma", types: ["fire"] },
  { id: 219, name: "Magcargo", types: ["fire", "rock"] },
  { id: 220, name: "Swinub", types: ["ice", "ground"] },
  { id: 221, name: "Piloswine", types: ["ice", "ground"] },
  { id: 222, name: "Corsola", types: ["water", "rock"] },
  { id: 223, name: "Remoraid", types: ["water"] },
  { id: 224, name: "Octillery", types: ["water"] },
  { id: 225, name: "Delibird", types: ["ice", "flying"] },
  { id: 226, name: "Mantine", types: ["water", "flying"] },
  { id: 227, name: "Skarmory", types: ["steel", "flying"] },
  { id: 228, name: "Houndour", types: ["dark", "fire"] },
  { id: 229, name: "Houndoom", types: ["dark", "fire"] },
  { id: 230, name: "Kingdra", types: ["water", "dragon"] },
  { id: 231, name: "Phanpy", types: ["ground"] },
  { id: 232, name: "Donphan", types: ["ground"] },
  { id: 233, name: "Porygon2", types: ["normal"] },
  { id: 234, name: "Stantler", types: ["normal"] },
  { id: 235, name: "Smeargle", types: ["normal"] },
  { id: 236, name: "Tyrogue", types: ["fighting"] },
  { id: 237, name: "Hitmontop", types: ["fighting"] },
  { id: 238, name: "Smoochum", types: ["ice", "psychic"] },
  { id: 239, name: "Elekid", types: ["electric"] },
  { id: 240, name: "Magby", types: ["fire"] },
  { id: 241, name: "Miltank", types: ["normal"] },
  { id: 242, name: "Blissey", types: ["normal"] },
  { id: 243, name: "Raikou", types: ["electric"] },
  { id: 244, name: "Entei", types: ["fire"] },
  { id: 245, name: "Suicune", types: ["water"] },
  { id: 246, name: "Larvitar", types: ["rock", "ground"] },
  { id: 247, name: "Pupitar", types: ["rock", "ground"] },
  { id: 248, name: "Tyranitar", types: ["rock", "dark"] },
  { id: 249, name: "Lugia", types: ["psychic", "flying"] },
  { id: 250, name: "Ho-Oh", types: ["fire", "flying"] },
  { id: 251, name: "Celebi", types: ["psychic", "grass"] },
];

const REGION_LABELS = { kanto: "Kanto", johto: "Johto" };

// Lista combinada com a região marcada em cada Pokémon.
const POKEMON = [
  ...KANTO.map((p) => ({ ...p, region: "kanto" })),
  ...JOHTO.map((p) => ({ ...p, region: "johto" })),
];
