// Pokémon da região de Johto (Pokédex Nacional Nº 152–251).
// type usa as chaves em inglês (para cores/sprites); o rótulo PT vem de TYPE_LABELS.
const TYPE_LABELS = {
  normal: "Normal", fire: "Fogo", water: "Água", grass: "Planta",
  electric: "Elétrico", ice: "Gelo", fighting: "Lutador", poison: "Veneno",
  ground: "Terra", flying: "Voador", psychic: "Psíquico", bug: "Inseto",
  rock: "Pedra", ghost: "Fantasma", dragon: "Dragão", dark: "Noturno",
  steel: "Aço", fairy: "Fada",
};

const POKEMON = [
  { id: 152, name: "Chikorita", types: ["grass"] },
  { id: 153, name: "Bayleef", types: ["grass"] },
  { id: 154, name: "Meganium", types: ["grass"] },
  { id: 155, name: "Cyndaquil", types: ["fire"] },
  { id: 156, name: "Quilava", types: ["fire"] },
  { id: 157, name: "Typhlosion", types: ["fire"] },
  { id: 158, name: "Totodile", types: ["water"] },
  { id: 159, name: "Croconaw", types: ["water"] },
  { id: 160, name: "Feraligatr", types: ["water"] },
  { id: 161, name: "Sentret", types: ["normal"] },
  { id: 162, name: "Furret", types: ["normal"] },
  { id: 163, name: "Hoothoot", types: ["normal", "flying"] },
  { id: 164, name: "Noctowl", types: ["normal", "flying"] },
  { id: 165, name: "Ledyba", types: ["bug", "flying"] },
  { id: 166, name: "Ledian", types: ["bug", "flying"] },
  { id: 167, name: "Spinarak", types: ["bug", "poison"] },
  { id: 168, name: "Ariados", types: ["bug", "poison"] },
  { id: 169, name: "Crobat", types: ["poison", "flying"] },
  { id: 170, name: "Chinchou", types: ["water", "electric"] },
  { id: 171, name: "Lanturn", types: ["water", "electric"] },
  { id: 172, name: "Pichu", types: ["electric"] },
  { id: 173, name: "Cleffa", types: ["fairy"] },
  { id: 174, name: "Igglybuff", types: ["normal", "fairy"] },
  { id: 175, name: "Togepi", types: ["fairy"] },
  { id: 176, name: "Togetic", types: ["fairy", "flying"] },
  { id: 177, name: "Natu", types: ["psychic", "flying"] },
  { id: 178, name: "Xatu", types: ["psychic", "flying"] },
  { id: 179, name: "Mareep", types: ["electric"] },
  { id: 180, name: "Flaaffy", types: ["electric"] },
  { id: 181, name: "Ampharos", types: ["electric"] },
  { id: 182, name: "Bellossom", types: ["grass"] },
  { id: 183, name: "Marill", types: ["water", "fairy"] },
  { id: 184, name: "Azumarill", types: ["water", "fairy"] },
  { id: 185, name: "Sudowoodo", types: ["rock"] },
  { id: 186, name: "Politoed", types: ["water"] },
  { id: 187, name: "Hoppip", types: ["grass", "flying"] },
  { id: 188, name: "Skiploom", types: ["grass", "flying"] },
  { id: 189, name: "Jumpluff", types: ["grass", "flying"] },
  { id: 190, name: "Aipom", types: ["normal"] },
  { id: 191, name: "Sunkern", types: ["grass"] },
  { id: 192, name: "Sunflora", types: ["grass"] },
  { id: 193, name: "Yanma", types: ["bug", "flying"] },
  { id: 194, name: "Wooper", types: ["water", "ground"] },
  { id: 195, name: "Quagsire", types: ["water", "ground"] },
  { id: 196, name: "Espeon", types: ["psychic"] },
  { id: 197, name: "Umbreon", types: ["dark"] },
  { id: 198, name: "Murkrow", types: ["dark", "flying"] },
  { id: 199, name: "Slowking", types: ["water", "psychic"] },
  { id: 200, name: "Misdreavus", types: ["ghost"] },
  { id: 201, name: "Unown", types: ["psychic"] },
  { id: 202, name: "Wobbuffet", types: ["psychic"] },
  { id: 203, name: "Girafarig", types: ["normal", "psychic"] },
  { id: 204, name: "Pineco", types: ["bug"] },
  { id: 205, name: "Forretress", types: ["bug", "steel"] },
  { id: 206, name: "Dunsparce", types: ["normal"] },
  { id: 207, name: "Gligar", types: ["ground", "flying"] },
  { id: 208, name: "Steelix", types: ["steel", "ground"] },
  { id: 209, name: "Snubbull", types: ["fairy"] },
  { id: 210, name: "Granbull", types: ["fairy"] },
  { id: 211, name: "Qwilfish", types: ["water", "poison"] },
  { id: 212, name: "Scizor", types: ["bug", "steel"] },
  { id: 213, name: "Shuckle", types: ["bug", "rock"] },
  { id: 214, name: "Heracross", types: ["bug", "fighting"] },
  { id: 215, name: "Sneasel", types: ["dark", "ice"] },
  { id: 216, name: "Teddiursa", types: ["normal"] },
  { id: 217, name: "Ursaring", types: ["normal"] },
  { id: 218, name: "Slugma", types: ["fire"] },
  { id: 219, name: "Magcargo", types: ["fire", "rock"] },
  { id: 220, name: "Swinub", types: ["ice", "ground"] },
  { id: 221, name: "Piloswine", types: ["ice", "ground"] },
  { id: 222, name: "Corsola", types: ["water", "rock"] },
  { id: 223, name: "Remoraid", types: ["water"] },
  { id: 224, name: "Octillery", types: ["water"] },
  { id: 225, name: "Delibird", types: ["ice", "flying"] },
  { id: 226, name: "Mantine", types: ["water", "flying"] },
  { id: 227, name: "Skarmory", types: ["steel", "flying"] },
  { id: 228, name: "Houndour", types: ["dark", "fire"] },
  { id: 229, name: "Houndoom", types: ["dark", "fire"] },
  { id: 230, name: "Kingdra", types: ["water", "dragon"] },
  { id: 231, name: "Phanpy", types: ["ground"] },
  { id: 232, name: "Donphan", types: ["ground"] },
  { id: 233, name: "Porygon2", types: ["normal"] },
  { id: 234, name: "Stantler", types: ["normal"] },
  { id: 235, name: "Smeargle", types: ["normal"] },
  { id: 236, name: "Tyrogue", types: ["fighting"] },
  { id: 237, name: "Hitmontop", types: ["fighting"] },
  { id: 238, name: "Smoochum", types: ["ice", "psychic"] },
  { id: 239, name: "Elekid", types: ["electric"] },
  { id: 240, name: "Magby", types: ["fire"] },
  { id: 241, name: "Miltank", types: ["normal"] },
  { id: 242, name: "Blissey", types: ["normal"] },
  { id: 243, name: "Raikou", types: ["electric"] },
  { id: 244, name: "Entei", types: ["fire"] },
  { id: 245, name: "Suicune", types: ["water"] },
  { id: 246, name: "Larvitar", types: ["rock", "ground"] },
  { id: 247, name: "Pupitar", types: ["rock", "ground"] },
  { id: 248, name: "Tyranitar", types: ["rock", "dark"] },
  { id: 249, name: "Lugia", types: ["psychic", "flying"] },
  { id: 250, name: "Ho-Oh", types: ["fire", "flying"] },
  { id: 251, name: "Celebi", types: ["psychic", "grass"] },
];
